# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d1641a5ac4f6bf2a497b72b06ae26f275756eac187bbb0877901cd0bf57b1ceaa64662d69528c534a55627d48e1af5e24724f18c3dc61082f4d5e9e6cf1bbda0

test:
  secret_key_base: 9f636af415b80523876cf306abc3bc51cc14341ef959cae2c59bebc7c29a0fae6a6fad74d6ab8f23ff191b84e900e714a44c6f89ae9495a4e7a3e246d68bedec

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
